# Generated by Django 2.1.5 on 2019-02-17 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0004_note_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=10)),
                ('hourStart', models.CharField(max_length=5)),
                ('hourEnd', models.CharField(max_length=5)),
                ('classroom', models.CharField(max_length=10)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic.Subject')),
            ],
        ),
    ]
