# Generated by Django 2.1.5 on 2019-02-05 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190131_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.Period'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Note'),
        ),
    ]
