# Generated by Django 2.1.5 on 2019-02-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_period_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Student'),
        ),
    ]
