# Generated by Django 2.1.5 on 2019-02-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190205_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.Period'),
        ),
    ]
