# Generated by Django 2.1.5 on 2019-02-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_student_periods'),
        ('schedule', '0006_auto_20190206_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Student'),
        ),
    ]
