# Generated by Django 2.1.5 on 2019-02-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190131_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='periods',
        ),
    ]
