# Generated by Django 2.1.5 on 2019-01-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190128_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.User'),
        ),
    ]
